Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ebenoistS" do |s|
    s.vm.hostname = "ebenoistS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |v|
      v.name = "ebenoistS"
      v.cpus = 1
      v.memory = 2048
    end
    s.vm.provision "shell", path: "scripts/server.sh"
  end
end
