Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ebenoistS" do |s|
    s.vm.hostname = "ebenoistS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |v|
      v.name = "ebenoistS"
      v.cpus = 1
      v.memory = 1024
    end
    s.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "ebenoistSW" do |w|
    w.vm.hostname = "ebenoistSW"
    w.vm.network "private_network", ip: "192.168.56.111"
    w.vm.provider "virtualbox" do |v|
      v.name = "ebenoistSW"
      v.cpus = 1
      v.memory = 1024
    end
    w.vm.provision "shell", path: "scripts/worker.sh"
  end
end
